remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Andrea Ferrer Hamilton - Software Developer
description: A portfolio website to showcase skills as a software developer
